### ISSUE TITLE
Version Pinning With `p2deps`

### ISSUE THREAD

**Issue by fullben** [equodev/equo-ide#119]
I'm quite new to the topic of P2, so in case this is a somewhat stupid question I'd like to apologize in advance here :)

I was wondering if it is possible to somehow specify a version (range) for a dependency when using the `p2deps` plugin for pulling a project dependency from a P2 repository?

**Comment by nedtwigg** [comment]
That is not currently possible in our p2 client.

The way we handle version pinning is by pinning the update sites, e.g.

- https://download.eclipse.org/eclipse/updates/4.26/ 
- we use ^ instead of v
- https://download.eclipse.org/eclipse/updates/

Do you have an example where this isn't sufficient?

**Comment by fullben** [comment]
I see.

Well, in my use case, I have a repository with a 'generic' address, something along the line of _https://download.some-domain.com_. As far as I can tell, I'm only seeing the latest artifacts.

I think I'll try to contact the repository host to understand what's going on there and if I could pin the update site.

**Comment by nedtwigg** [comment]
> I think I'll try to contact the repository host to understand what's going on there and if I could pin the update site.

That's a good idea. Probably they are doing something like this:

```
https://download.some-domain.com/1.0
https://download.some-domain.com/1.1
https://download.some-domain.com/1.2
https://download.some-domain.com (composite p2 repo that points to latest, happens to be 1.2 right now)
```

And if they aren't doing that, I would try asking them to start doing it!
