### ISSUE TITLE
Documentation for "dev.equo.p2deps"

### ISSUE THREAD

**Issue by dhakehurst** [equodev/equo-ide#158]
Please provide some documentation on how to use this

**Comment by nedtwigg** [comment]
Thanks for taking a look! Does the example in

- #159 

explain it? Let me know if anything isn't clear and I'll try to improve it.

**Comment by dhakehurst** [comment]
Its a bit minimal, and does not show how to convert, see diffplug/goomph#209

**Comment by nedtwigg** [comment]
Roger, I'll keep Goomph-related conversion info in the Goomph project.
