### ISSUE TITLE
Error trying to run equo-ide

### ISSUE THREAD

**Issue by agustinschilling** [equodev/equo-ide#19]
Hi!, 
When I try to run the following command:  "mvn equo-ide:launch" inside example-maven or "gradle equoIde" inside example-gradle I get the following exception:

![Captura de pantalla de 2022-12-07 13-19-48](https://user-images.githubusercontent.com/64040737/206235056-e6e3977f-8649-44f1-be92-1ae9a78bf5c0.png)

I tried adding the missing dependency "junit-jupiter-migrationsupport" and no success.

What could i try?

Thanks in advance
Agustin of Equo team.

**Comment by nedtwigg** [comment]
This is a known bug in the currently released version. #15 has to get finished (currently works on mac, has bugs on win & linux). When that gets merged then this issue should be resolved.
