### ISSUE TITLE
Resolving way too many dependencies?

### ISSUE THREAD

**Issue by tr7zw** [equodev/equo-ide#37]
Hey there, wanted to give this a try to see how its current state is, but Maven just fell into a pit of loading pom/maven-metadata files.
I just stopped it after a few mins, and the log was so big, that I couldn't even paste the full thing anywhere. A shorter version of the start: https://paste.md-5.net/vezofegoyo.cs
It seems to load a ton of redundant versions, for example:
```
org.eclipse.jface-3.12.1.pom
org.eclipse.jface-3.12.2.pom
org.eclipse.jface-3.13.0.pom
org.eclipse.jface-3.13.1.pom
org.eclipse.jface-3.13.2.pom
org.eclipse.jface-3.14.0.pom
org.eclipse.jface-3.14.100.pom
org.eclipse.jface-3.15.0.pom
org.eclipse.jface-3.15.100.pom
org.eclipse.jface-3.16.0.pom
org.eclipse.jface-3.17.0.pom
org.eclipse.jface-3.18.0.pom
org.eclipse.jface-3.18.0.pom
org.eclipse.jface-3.20.0.pom
org.eclipse.jface-3.21.0.pom
org.eclipse.jface-3.22.0.pom
org.eclipse.jface-3.22.100.pom
org.eclipse.jface-3.22.200.pom
org.eclipse.jface-3.23.0.pom
org.eclipse.jface-3.24.0.pom
org.eclipse.jface-3.25.0.pom
org.eclipse.jface-3.26.0.pom
org.eclipse.jface-3.27.0.pom
org.eclipse.jface-3.28.0.pom
```

**Comment by nedtwigg** [comment]
Thanks for reporting! This bug is maven-specific, we're doing something wrong with how we ask maven for dependencies

https://github.com/equodev/equo-ide/blob/0b98ad56fb630fa09ed3eead5a57c255c5005626/plugin-maven/src/main/java/dev/equo/ide/maven/LaunchMojo.java#L108-L113

The good news is that regardless of what we *were* doing wrong, I think we can sidestep the issue entirely with our new p2 resolver. Should be fixed next week.

**Comment by tr7zw** [comment]
Sounds good. I maintain a ton of smaller gradle projects, where IntelliJ(which a lot of people use) fails to work correctly. Being able to provide a setup that is "just call this command and it opens a fully prepared Eclipse IDE with all the right settings, formatter, plugins, projects, etc" sounds like a neat thing to try out.

**Comment by nedtwigg** [comment]
The fix is in the main branch, I'll post on this issue again when it's in a published release on mavenCentral.

**Comment by nedtwigg** [comment]
This fix (and others) is live in maven plugin `0.7.0`. It'll be a lot more useful after a few more features get added, but there's enough working that it's probably worth taking a look at again :)

https://github.com/equodev/equo-ide/blob/main/plugin-maven/example-maven/pom.xml

**Comment by tr7zw** [comment]
Yep, it now launched one IDE window for each subproject. Shouldn't it only open for the top project, and later import the subprojects into the same workspace?
Seems like they don't yet have the maven/gradle plugin included, to be able to import the project?

**Comment by nedtwigg** [comment]
> Yep, it now launches one IDE window for each subproject

Uh-oh! Just curious, did you add a `<plugin>` block for EquoIDE into your `pom.xml`? Or you were running it globally? My guess is globally, and we'll need to add a hook to detect the existence of a parent project...

> they don't yet have the maven/gradle plugin included, to be able to import the project?

Correct!

- #17
- #18

**Comment by tr7zw** [comment]
I followed the readme, so added the plugin block to the parent pom and ran ``mvn equo-ide:launch``. This parent pom is of type ``<packaging>pom</packaging>`` and contains 5 ``modules``, each of which opened one IDE. The plugin probably gets applied to all submodules, invoking it once for each one. Not sure how to tell maven not to do that, for Gradle this should be straightforward (just don't add it to the ``submodules`` or ``allprojects`` node).
