### ISSUE TITLE
Public CI

### ISSUE THREAD

**Issue by nedtwigg** [equodev/equo-ide#5]
I'm happy to use any CI platform so long as it supports

- run tests on every commit (duh)
- manual job running from dashboard (not all CI platforms do this)

Right now I use CircleCI for most of my projects. I use the manual job so that I can press a button and publish a new release, e.g.

https://app.circleci.com/pipelines/github/diffplug/goomph/172/workflows/1646445a-a67d-4b34-8858-2e77bfec9707

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/2924992/203668453-0dfaf67c-04f7-425d-85b7-444614cc9ae5.png">

(I press release)

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/2924992/203668506-431e84f3-8412-4759-af0b-1d6940643aae.png">

If you prefer a different CI platform that's fine with me.

**Comment by nedtwigg** [comment]
@lonelion I added a GitLab CI file, can you enable CI on this repo?

https://github.com/equodev/equo-ide/blob/main/.gitlab-ci.yml

**Comment by lonelion** [comment]
@nedtwigg you want me to create a Gitlab CI/CD project to connect this repo to Gitlab?

**Comment by nedtwigg** [comment]
Done, we went with GitHub Actions.
