### ISSUE TITLE
Question about Atomos and start levels

### ISSUE THREAD

**Issue by nedtwigg** [equodev/equo-ide#67]
Hi @tjwatson, I have a question about Atomos+Equinox, startlevels, and lazy activation policy. I'm not entitled to your time, so if you have any links to drop or general hints towards how to emulate the startlevel + lazy activation behavior of regular Eclipse using Atomos, that would be very helpful! If you have time, I'll dig into detail below, but no worries if you don't have time.

------------

On the branch `feat/buildship`, we are using Atomos in a very plain way. We are not using `atomos.content.install=false` nor `atomos.content.start=false`. We're just using the Atomos defaults.

https://github.com/equodev/equo-ide/blob/9c067d8878a3ef71d123f0f031d3254c98971e32/solstice/src/main/java/dev/equo/solstice/AtomosFrontend.java#L99-L108

We are modifying headers to strip a lot of detail out of Import/Export/Require.

https://github.com/equodev/equo-ide/blob/9c067d8878a3ef71d123f0f031d3254c98971e32/solstice/src/main/java/dev/equo/solstice/AtomosFrontend.java#L75-L81

https://github.com/equodev/equo-ide/blob/9c067d8878a3ef71d123f0f031d3254c98971e32/solstice/src/main/java/dev/equo/solstice/SolsticeManifest.java#L235-L242

https://github.com/equodev/equo-ide/blob/9c067d8878a3ef71d123f0f031d3254c98971e32/solstice/src/main/java/dev/equo/solstice/SolsticeManifest.java#L278-L292

And then removing any missing requirements

https://github.com/equodev/equo-ide/blob/9c067d8878a3ef71d123f0f031d3254c98971e32/solstice/src/main/java/dev/equo/solstice/SolsticeManifest.java#L171-L174

But when run as `gradlew IdeMainTest`

https://github.com/equodev/equo-ide/blob/9c067d8878a3ef71d123f0f031d3254c98971e32/solstice/build.gradle#L115-L118

And then open up the error log, we get lots of errors related to start order, e.g.

```
org.osgi.framework.BundleException: Exception in org.eclipse.debug.internal.ui.DebugUIPlugin.start() of bundle org.eclipse.debug.ui.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
...
Caused by: java.lang.IllegalStateException: Workbench has not been created yet.
	at org.eclipse.ui.PlatformUI.getWorkbench(PlatformUI.java:117)
	at org.eclipse.debug.internal.ui.contextlaunching.LaunchingResourceManager.startup(LaunchingResourceManager.java:545)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.getLaunchingResourceManager(DebugUIPlugin.java:341)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.start(DebugUIPlugin.java:550)
```

In our no-Atomos-pure-Solstice runtime, we handle this sort of thing by hardcoding which bundles use the workbench in their activator, and deferring their activation (and any bundle that relies on them) until after the workbench had started

https://github.com/equodev/equo-ide/blob/9c067d8878a3ef71d123f0f031d3254c98971e32/solstice/src/main/java/dev/equo/solstice/Solstice.java#L492-L500

https://github.com/equodev/equo-ide/blob/9c067d8878a3ef71d123f0f031d3254c98971e32/solstice/src/main/java/dev/equo/ide/IdeMainUi.java#L59-L66

I would like to activate bundles as eagerly and deterministically as possible, but some amount of laziness is required because so many activators rely on the Workbench having already been created. I think regular Eclipse handles this through laziness and not startorder, but maybe I'm wrong. Any tips?

**Comment by tjwatson** [comment]
Lazy activation is not something that can be done with non-OSGi framework class loaders.  Atomos just uses the the class loader used to load atomos itself so there is no hook from the class loader when a class is defined to allow a trigger to activate a lazy activated bundle.

You are correct that eclipse handles this through lazy activation.  But I've no good idea on how you would mimic that behavior in Atomos or Solstice.  You may need to result to do the start ordering in Atomos similar to how you do it for solstice.

It sounds like you already do some sorting with Solstice.  I would try to do that for Atomos by disabing the auto-starting in Atomos.  So it will install all the bundles but then you do post processing after they are installed to determine the order needed to start and then you can set the start-levels how you want to get the right order.

**Comment by nedtwigg** [comment]
I think I have solved the startLevel / lazy issue in

- #68

like so

https://github.com/equodev/equo-ide/blob/2df2f40de0a9195e52d65bd4dc46e502f7f3faea/solstice/src/main/java/dev/equo/ide/BuildPluginIdeMain.java#L252-L253

https://github.com/equodev/equo-ide/blob/ee425c0c8b41a6ec3512d1f73849ddd927b70427/solstice/src/main/java/dev/equo/ide/IdeMainUi.java#L60-L65

I think the problem I'm having now is unrelated to start levels (we've had this problem since the very beginning)...

```
java.lang.ClassNotFoundException: Can not load a class from a fragment bundle: org.eclipse.e4.ui.workbench.renderers.swt.cocoa_0.13.0.v20221111-1208 [165]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:615)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:89)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.internal.workbench.addons.HandlerProcessingAddon.processActiveHandler(HandlerProcessingAddon.java:141)
	at org.eclipse.e4.ui.internal.workbench.addons.HandlerProcessingAddon.postConstruct(HandlerProcessingAddon.java:55)
```

The handler in question has:

```
contributionURI = bundleclass://org.eclipse.e4.ui.workbench.renderers.swt.cocoa/org.eclipse.e4.ui.workbench.renderers.swt.cocoa.ArrangeWindowHandler
elementId = org.eclipse.e4.ui.workbench.renderers.swt.cocoa.ArrangeWindowHandler
contributorURI = platform:/fragment/org.eclipse.e4.ui.workbench.renderers.swt.cocoa
```

@tjwatson do you have any hints for where I should look?

**Comment by tjwatson** [comment]
I don't understand why that code is trying to load the class from the fragment bundle.  It should be resolving to load from the host bundle `org.eclipse.e4.ui.workbench.renderers.swt`.

**Comment by nedtwigg** [comment]
The start level issue was solved by

- #68

We fixed further start order issues in

- #71

We'll keep working on the fragment bundle issue, but the original point of this issue is solved. Thanks a ton @tjwatson!
